#!/bin/bash

function hello-typeform-init() {

  PROJECT_NAME="hello-typeform"
  REALPATH_CMD=$(get-realpath-cmd)
  PROJECT_DIR=$( dirname $(${REALPATH_CMD} $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ) )

}
