#!/bin/bash

function hello-go-init() {

  PROJECT_NAME="hello-go"
  REALPATH_CMD=$(get-realpath-cmd)
  PROJECT_DIR=$( dirname $(${REALPATH_CMD} $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ) )

}
