apiVersion: skaffold/v2alpha4
kind: Config
build:
  insecureRegistries:
    - registry.local:5000
    - registry.local:15000
  tagPolicy:
    envTemplate:
      template: "registry.local:5000/{{.IMAGE_NAME}}"
  artifacts:
  - image: hello-typeform
    docker:
      target: dev-env
    sync:
      manual:
      # NOTE: uncomment this to also watch/sync tests etc
      #- src: "src/**/*.go"
      #  dest: "/src"
      - src: "src/api*.go"
        dest: "/go/src/app"
        strip: "src"
      - src: "src/go.mod"
        dest: "/go/src/app"
        strip: "src"
      - src: "src/go.sum"
        dest: "/go/src/app"
        strip: "src"

deploy:
  kubectl:
    manifests:

profiles:
- name: local
  activation:
    - env: ENVIRONMENT=local
  deploy:
    kustomize:
      paths: ["kustomize/overlays/local"]

- name: staging
  activation:
    - env: ENVIRONMENT=staging
    - kubeContext: staging-hello-typeform
  deploy:
    kustomize:
      paths: ["kustomize/overlays/staging"]

# NOTE: as per [0] not possible to use custom deploy scripts yet
# [0] https://github.com/GoogleContainerTools/skaffold/issues/2277
- name: rio-poc
  activation:
    - env: ENVIRONMENT=rio-poc
  build:
    tagPolicy:
      envTemplate:
        template: "registry.local:15000/{{.IMAGE_NAME}}"
    artifacts:
    - image: hello-typeform
      docker:
        target: prod

  deploy:
    kubectl:
      manifests:
