apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: hello-go
        ports:
        - containerPort: 3001
        env:
          - name: ENVIRONMENT
            value: "local"
          - name: PORT
            value: "3000"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 3001
            port: liveness-port
          failureThreshold: 30
          periodSeconds: 10
