apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-go
  namespace: hello-go
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hello-go.local
    http:
      paths:
      - backend:
          serviceName: hello-go
          servicePort: 3000
